import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { I18nProvider } from "@/i18n/provider";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loadMessages(locale: string) {
  try {
    const mod = await import(`@/messages/${locale}.json`);
    return mod.default as Record<string, any>;
  } catch {
    const mod = await import("@/messages/vi.json");
    return mod.default as Record<string, any>;
  }
}

// Generate static params for all supported locales
export async function generateStaticParams() {
  return [
    { locale: "en" },
    { locale: "vi" },
    { locale: "zh" },
    { locale: "ko" },
  ];
}

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await loadMessages(locale);
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider locale={locale} messages={messages}>
          <Header />
          <main className="pt-16">{children}</main>
        </I18nProvider>
      </body>
    </html>
  );
}
